In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
#loading data
path = 'data\JER_data_fixed.csv'
df = pd.read_csv(path)

In [3]:
df.head()

,BP (hPa),RH (%),TD (degC),TDmax (degC),TDmin (degC),WDmax (deg),Ws1mm (m/s),Ws10mm (m/s),STDwd (deg),Wx,Wy,max Wx,max Wy,Day sin,Day cos,Year sin,Year cos
0,NaN,NaN,17.3,17.4,17.3,97.0,2.4,1.7,9.8,-0.332659,1.565036,-0.582153,2.738813,-5.461913e-12,1.000000,-0.004731,0.999989
1,NaN,NaN,17.0,17.0,16.9,58.0,2.9,2.2,14.2,0.400699,2.061417,0.686912,3.533858,2.588190e-01,0.965926,-0.004014,0.999992
2,NaN,NaN,17.3,17.3,17.2,92.0,2.1,2.1,16.2,-0.118586,1.695859,-0.167416,2.394154,5.000000e-01,0.866025,-0.003297,0.999995
3,NaN,NaN,16.7,16.8,16.7,75.0,1.8,1.9,8.6,0.234652,1.481533,0.312869,1.975377,7.071068e-01,0.707107,-0.002580,0.999997
4,NaN,NaN,16.6,16.6,16.5,84.0,2.0,1.8,9.6,-0.094205,1.797533,-0.125606,2.396711,8.660254e-01,0.500000,-0.001864,0.999998

In [4]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BP (hPa),160487.0,922.490836,3.683396,907.040000,919.760000,9.223000e+02,924.930000,937.440000
RH (%),160231.0,57.103195,24.117456,4.000000,37.000000,5.600000e+01,79.000000,100.000000
TD (degC),209755.0,17.955506,7.041178,-1.700000,12.100000,1.830000e+01,23.300000,41.600000
TDmax (degC),209760.0,18.084489,7.084270,-1.600000,12.300000,1.840000e+01,23.400000,42.000000
TDmin (degC),209757.0,17.829548,6.999501,-1.800000,12.000000,1.820000e+01,23.100000,41.400000
WDmax (deg),209856.0,235.435832,92.249904,0.000000,173.000000,2.730000e+02,301.000000,360.000000
Ws1mm (m/s),209647.0,4.489605,2.079202,0.000000,3.000000,4.300000e+00,5.700000,21.700000
Ws10mm (m/s),209655.0,3.590693,1.685942,0.000000,2.400000,3.400000e+00,4.600000,17.300000
STDwd (deg),209889.0,18.782293,9.497722,0.000000,13.000000,1.700000e+01,21.900000,99.900000
Wx,209644.0,0.565667,1.689057,-10.502361,-0.485148,6.237351e-01,1.720729,7.447818
Wy,209644.0,-1.898592,2.650842,-14.464068,-3.731412,-2.318222e+00,0.000000,8.893634
max Wx,209646.0,0.905407,2.888968,-18.950462,-0.900863,1.057716e+00,2.907803,13.098794
max Wy,209646.0,-3.266978,4.535368,-26.140252,-6.373896,-4.019600e+00,0.000000,15.259103
Day sin,210117.0,-0.000164,0.707161,-1.000000,-0.707107,-7.070258e-14,0.707107,1.000000
Day cos,210117.0,-0.000047,0.707056,-1.000000,-0.707107,8.192532e-15,0.707107,1.000000
Year sin,210117.0,0.000252,0.707118,-1.000000,-0.706779,3.607805e-04,0.707388,1.000000
Year cos,210117.0,-0.000375,0.707098,-1.000000,-0.707423,-7.442590e-04,0.706817,1.000000

In [5]:
length = float(len(df['TD (degC)']))
length = length / 24

In [6]:
len(df['TD (degC)'])

210117

In [7]:
# Determine the size of each chunk, assuming the data is evenly distributed across the years
chunk_size = len(df['TD (degC)']) // 24

# Split the data into 24 chunks
chunks = [df['TD (degC)'][i*chunk_size:(i+1)*chunk_size] for i in range(24)]

# Calculate the average of each chunk
averages = [chunk.mean() for chunk in chunks]

averages

[17.043214816508513,
 17.795543815321004,
 17.487607179604435,
 17.385152588867296,
 17.427062857142857,
 17.415681792204822,
 17.37631729340496,
 17.572439414723366,
 17.965744972577696,
 17.89244744058501,
 19.70066308448611,
 17.05069730224051,
 18.335532182462558,
 17.87855102274026,
 18.228403246085264,
 18.103653336406587,
 18.451982177539126,
 18.164526448074948,
 18.707985833428538,
 17.945941860465116,
 18.178981037240117,
 18.53296376728769,
 17.694514285714284,
 18.609482463155487]